# Generated by Django 2.0.4 on 2018-04-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_begin', models.DateTimeField(verbose_name='date of beginning')),
                ('date_end', models.DateTimeField(verbose_name='date of closing')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Schedule'),
        ),
    ]
