# Generated by Django 2.0.4 on 2018-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
