# Generated by Django 2.0.4 on 2018-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180409_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
