# Generated by Django 2.0.4 on 2018-04-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180409_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
